[package]
name = "simulation"
version.workspace = true
edition.workspace = true

[dependencies]
proto = { path = "../proto" }
storage = { path = "../storage" }
raft-engine = { path = "../raft-engine" }
txn-coordinator = { path = "../txn-coordinator" }
node = { path = "../node" }
tokio = { workspace = true }
tonic = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
raft = "0.7.0"
criterion = { version = "0.5", features = ["async_tokio"] }

[[bench]]
name = "transaction_bench"
harness = false